rvm: 2.3.0

cache: bundler

matrix:
  allow_failures:
    - rvm: ruby-head

env:
  - MARKET_TOWN=brochure GOPATH=$PWD/gopath
  - MARKET_TOWN=checkout RAKE_TASK=rubocop
  - MARKET_TOWN=checkout RAKE_TASK=common_spec
  - MARKET_TOWN=checkout RAKE_TASK=spree_spec
  - MARKET_TOWN=checkout RAKE_TASK=solidus_spec

install:
  - bundle install
  - bundle exec rake travis:install

script: bundle exec rake travis:script

notifications:
  slack: madetechteam:be3g1qE6so2p2UcqQiOGBRUs
