rvm:
  - 2.2
  - 2.3.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

install:
  - pushd checkout && BUNDLE_GEMFILE=$PWD/Gemfile bundle install && popd
  - pushd checkout && BUNDLE_GEMFILE=$PWD/Gemfile.solidus.rb bundle install && popd
  - pushd checkout && BUNDLE_GEMFILE=$PWD/Gemfile.spree.rb bundle install && popd

script:
  - pushd checkout && BUNDLE_GEMFILE=$PWD/Gemfile bundle exec rake && popd

notifications:
  slack: madetechteam:be3g1qE6so2p2UcqQiOGBRUs
