rvm: 2.2

cache:
  directories:
    - checkout/vendor

env:
  - MARKET_TOWN=brochure GOPATH=$PWD/gopath
  - MARKET_TOWN=checkout RAKE_TASK=rubocop
  - MARKET_TOWN=checkout RAKE_TASK=common_spec
  - MARKET_TOWN=checkout RAKE_TASK=spree_spec
  - MARKET_TOWN=checkout RAKE_TASK=solidus_spec

install:
  - bundle install
  - bundle exec rake travis:install

script:
  - bundle exec rake travis:script

notifications:
  slack: madetechteam:be3g1qE6so2p2UcqQiOGBRUs
