rvm:
  - 2.2
  - 2.3.0
  - ruby-head

install:
  - pushd checkout && bundle install && popd

script:
  - pushd checkout && BUNDLE_GEMFILE=$PWD/Gemfile bundle exec rake && popd

notifications:
  slack: madetechteam:be3g1qE6so2p2UcqQiOGBRUs
